### ISSUE TITLE
Meeting with the client

### ISSUE THREAD

**Issue by byronkamal** [fga-eps-mds/2019.2-Gymnasteg-Wiki#19]
## Description

Meet with client to understand the problem.

## Tasks
- [x] meet with the client
- [x] understand the problem
- [x] take notes about the theme

**When:** UnB-Gama Sala 21
**Time:** 2pm
